config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;


return static function (RouteBuilder $routes) {
    /*
     * The default class to use for all routes
     *
     * The following route classes are supplied with CakePHP and are appropriate
     * to set as the default:
     *
     * - Route
     * - InflectedRoute
     * - DashedRoute
     *
     * If no call is made to `Router::defaultRouteClass()`, the class used is
     * `Route` (`Cake\Routing\Route\Route`)
     *
     * Note that `Route` does not do any inflections on URLs which will result in
     * inconsistently cased URLs when used with `:plugin`, `:controller` and
     * `:action` markers.
     */
    $routes->setRouteClass(DashedRoute::class);

    $routes->scope('/', function (RouteBuilder $builder) {
        $builder->connect('/', ['controller' => 'Pages', 'action' => 'display', '']);
        $builder->connect('/pages/*', 'Pages::display');
        $builder->fallbacks();

        

    });

    /*
     * If you need a different set of middleware or none at all,
     * open new scope and define routes there.
     *
     * ```
     * $routes->scope('/api', function (RouteBuilder $builder) {
     *     // No $builder->applyMiddleware() here.
     *
     *     // Parse specified extensions from URLs
     *     // $builder->setExtensions(['json', 'xml']);
     *
     *     // Connect API actions here.
     * });
     * ```
     */
    
};

src/Model/Table/LikesTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Reactions Model
 *
 * @property \App\Model\Table\UsersTable&\Cake\ORM\Association\BelongsTo $Users
 * @property \App\Model\Table\PostsTable&\Cake\ORM\Association\BelongsTo $Posts
 * @method \App\Model\Entity\Reaction newEmptyEntity()
 * @method \App\Model\Entity\Reaction newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Reaction[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Reaction get($primaryKey, $options = [])
 * @method \App\Model\Entity\Reaction findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\Reaction patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Reaction[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Reaction|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Reaction saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Reaction[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Reaction[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Reaction[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Reaction[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class LikesTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('likes');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
        ]);
        $this->belongsTo('Posts', [
            'foreignKey' => 'post_id',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->dateTime('deleted')
            ->allowEmptyDateTime('deleted');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules): RulesChecker
    {
        $rules->add($rules->existsIn('user_id', 'Users'), ['errorField' => 'user_id']);
        $rules->add($rules->existsIn('post_id', 'Posts'), ['errorField' => 'post_id']);

        return $rules;
    }
}

src/Controller/ProfileController.php
<?php
declare(strict_types=1);

namespace App\Controller;

use Cake\ORM\TableRegistry;

/**
 * Posts Controller
 *
 * @property \App\Model\Table\PostsTable $Posts
 * @method \App\Model\Entity\Post[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ProfileController extends AppController
{
    public function initialize(): void
    {
        parent::initialize();
        $this->viewBuilder()->setLayout('app');
        $this->loadModel('Posts');
        $this->loadModel('Users');
        $this->loadModel('SharePosts');
        $this->loadModel('Likes');
        $this->loadModel('Comments');
        $this->loadModel('Followers');
    }

    public function beforeFilter(\Cake\Event\EventInterface $event)
    {
        parent::beforeFilter($event);
        $this->Authentication->addUnauthenticatedActions(['login']);
        $this->Authentication->addUnauthenticatedActions(['login', 'add']);
    }

    public function profile($user_id = null)
    {
        $identity = $this->request->getAttribute('authentication')->getIdentity();
        $users = TableRegistry::get('Users');
        $user = $users->find()
            ->where(['id' => $user_id])
            ->all();
        $key = $this->request->getQuery('key');
        if ($key) {
            $posts = $this->Posts
            ->find('all')
            ->contain(['Users'])
            ->where(['fullname like' => '%' . $key . '%'])
            ->all();
        } else {
             $posts = $this->Posts->find('all')
                ->contain(['Users'])
                ->where(['user_id' => $user_id])
                ->order(['Posts.id' => 'desc'])
                ->all();
        }
         $sharePosts = $this->SharePosts->find('all', ['withDeleted'])
                ->contain(['Posts'])
                ->contain(['Users'])
                ->where(['SharePosts.user_id' => $user_id])
                ->all();
        $this->set(compact('user', 'posts', 'identity', 'sharePosts'));
    }
}

templates/Profile/profile.php
<br>
  <?php
    echo $this->Form->create(null,['type' => 'get']);
    echo $this->Form->control('key',['label' => 'Search', 'value' => $this->request->getQuery('key'),'class' => 'form-control me-sm-2']);
    echo  $this->Form->submit(__('Search'),['class' => 'btn btn-primary']);
    echo $this->Form->end();
  ?>
  <?= $this->Html->link(__('New Post'), [ 'controller' => 'Posts','action' => 'add'], ['class' => 'button float-right']) ?>
  <div class="off-canvas-wrapper">
      <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
        <div class="off-canvas-content" data-off-canvas-content>
        <div class="container mt-4 mb-4 p-3 d-flex justify-content-center"> 
           <?php foreach ($user as $user): ?>
            <div class="card p-4" id="card-body">
              <?php if ($identity->id == $user->id): ?>
                <div class=" image d-flex flex-column justify-content-center align-items-center">
                <?php echo $this->Html->image(h($user->profile_pic), array(
                	'width'=>'200px',
                	'url' => array(
                             'controller' => 'Profile',
                             'action' => 'profile', h($user->id)
                    )            	
                ));?>
                 <span id="fullname" style="text-transform: capitalize;" class="name mt-3"><?= h($user->fullname) ?></span>
                    <div class="d-flex flex-row justify-content-center align-items-center mt-3"><?= $this->Html->link(__('Followers'), ['controller' => 'Followers','action' => 'listfollower' , $user->id], ['class' => 'btn btn-primary']) ?> 
                    &nbsp&nbsp&nbsp 
                    <?= $this->Html->link(__('Following'), ['controller' => 'Followers','action' => 'followings' , h($user->id)], ['class' => 'btn btn-primary']) ?></div>
                    <div class=" d-flex mt-2">
                  		<?php echo $this->Html->link('Edit Profile'
                  			,array('controller' => 'Users', 'action'=>'edit',h( $user->id))
                   			,array('class' => 'btn1 btn-dark')); 
                   		?>
                  	</div>
                   

                    <div class=" px-2 rounded mt-4 date "> <span class="join">Joined <?= h($user->created) ?></span> </div>
                </div>
              <?php endif ?>
              <?php  if ($identity->id != $user->id): ?>
                <input hidden="" value="<?= h($user->id) ?>" id="user_id" type="text" required class="form-control" placeholder="idHolder" name="user_id">
                <div class=" image d-flex flex-column justify-content-center align-items-center"><?php echo $this->Html->image(h($user->profile_pic), array(
                  'width'=>'200px',
                  'url' => array(
                             'controller' => 'Profile',
                             'action' => 'profile', h($user->id)
                    )             
                ));?>

                 <span style="text-transform: capitalize;" class="name mt-3"><?= h($user->fullname) ?></span>
                   <div class="d-flex flex-row justify-content-center align-items-center mt-3">
                     <button id="followBtn" type="button" class="btn btn-primary">Follow</button>
                   </div>
                    <div class=" px-2 rounded mt-4 date "> <span class="join">Joined <?= h($user->created) ?></span> </div>
                </div>
              <?php endif ?>
                </div>
                 <?php endforeach ?>       
            </div>
             <?php foreach ($posts as $post): ?>      
            <div id="try" class="row medium-8 large-7 columns ">
              <div class="blog-post">
                <h3 style="text-transform: capitalize;"><?= h($post->title) ?> </h3>
              <strong>
                <?= $this->Html->link(__(h($post->user->fullname)), ['controller' => 'profile','action' => 'profile', h($post->user_id)],['style' => 'text-transform: capitalize;']) ?>
              </strong>
                <p> <?= h($post->description) ?> </p>
              <?php if (h($post->file_name) != '') : ?>
                <?php echo $this->Html->image(h($post->file_name), 
                  array(
                  "alt" => "logo",
                  'url' => array(
                             'controller' => 'Posts',
                             'action' => 'view', h($post->id)
                    )
                  )
                ); ?>
              </div>
          </div><br>
          <?php endif ?>
       <?php endforeach ?>
       <?php foreach ($sharePosts as $share): ?>
        <?php if($share->post->deleted != null): ?>
         <div id="try" class="row medium-8 large-7 columns ">
              <div class="blog-post">
               <div class="card border-danger mb-3" style="max-width: 20rem;">
                <div class="card-header">Content Not found</div>
                <div class="card-body">
                  <p class="card-text">The page you requested cannot be displayed right now.</p>
                </div>
              </div>
              </div>
          </div><br>
        <?php endif ?>
        <?php if($share->post->deleted == null): ?>
             <div id="try" class="row medium-8 large-7 columns ">
              <div class="blog-post">
              <div class="card border-primary mb-3" style="max-width: 20rem;">
                    <div class="card-header">Your share this posts</div>
                    <div class="card-body">
                      <h4 class="card-title"><?= $this->Html->link(__(h($share->user->fullname)), ['controller' => 'profile','action' => 'profile', $share->user_id],['style' => 'text-transform: capitalize;']) ?></h4>
                        <h3 style="text-transform: capitalize;"><?= h($share->post->title) ?> </h3>
                      <p class="card-text"><?= h($share->post->description) ?></p>
                      <?php if ($share->post->file_name != '') : ?>
                            <?php echo $this->Html->image(h($share->post->file_name), 
                              array(
                              "alt" => "logo",
                              'url' => array(
                                         'controller' => 'Posts',
                                         'action' => 'view', h($share->post->id)
                                )
                              )
                            ); ?>
                          <?php endif ?>
                    </div>
              </div>
              </div>
</div><br>
        <?php endif ?>
       <?php endforeach ?>
        </div>
          <hr>
        </div>
      </div>
  </div>
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
<script type="text/javascript">
$(function(){
  $.ajaxSetup({
      headers: {
        'X-CSRF-TOKEN': csrfToken 
      }
  });
 
  
   $('#followBtn').click(function(){
    var following  = $('#user_id').val();
    $.ajax({
        method: "POST",
        url: "<?= $this->Url->build(['controller' => 'followers', 'action' => 'add']) ?>",
        data:{ 
         following: following
        },
        success:function(response){
                location.reload();
            }
      });

  });
});

</script>